tasks:
  - init: npm install && npm run build
    command: npm start
  - command: echo "To create a new blog, type; npm run create:blog"
ports:
  - port: 8000
    onOpen: open-preview
github:
  prebuilds:
    master: true
    branches: true
    pullRequestsFromForks: true
    addComment: true
