name: Merge Schedule
on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize
  schedule:
    # every day at 15:00 UTC https://crontab.guru/#0_15_*_*_*
    - cron: '0 15 * * *'
jobs:
  merge_schedule:
    runs-on: ubuntu-latest
    steps:
      - uses: gr2m/merge-schedule-action@v2
        with:
          merge_method: merge
          require_statuses_success: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
